[phases.setup]
nixPkgs = ["python310"]

[phases.build]
cmds = ["python3.10 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python3.10 bot.py"
